name: Deploy Backend (production)

on:
  push:
    branches: [release]

jobs:
  backend:
    name: Deploy Backend to VPS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 212.85.2.8 >> ~/.ssh/known_hosts

      - name: Criar .env remoto
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@212.85.2.8 "cat <<EOF > /var/www/prod/spingo-backend/.env
            PORT=${{ secrets.PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            PAGARME_SECRET_KEY=${{ secrets.PAGARME_SECRET_KEY }}
          EOF"

      - name: Deploy Backend
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@212.85.2.8 << 'EOF'
            cd /var/www/prod/spingo-backend
            git pull origin release
            npm install
            npm run build
             PORT=4200 NODE_ENV=production pm2 restart spingo-backend-prod --update-env || \
              PORT=4200 NODE_ENV=production pm2 start dist/index.js --name spingo-backend-prod
            pm2 save
          EOF